; day 16
(defvar data "10001110011110000")
; (defvar len 35651584)
(defvar len 272)
(defvar tmp "")
(defvar cksum "")
(defvar part "")
(defvar i 0)
(defvar bits 0)

(print "Filling data")
(loop while (< (length data) len)
    do (setf tmp (substitute #\0 #\2 (substitute #\1 #\0 (substitute #\2 #\1 (reverse data)))))
    do (setf data (concatenate 'string data "0"))
    do (setf data (concatenate 'string data tmp)))

(setf i len)
(loop while (= (mod i 2) 0)
	do (setf i (/ i 2)))

(setf bits (/ len i))

(print "Calculating checksum")
(setf data (subseq data 0 len))
(loop while (> (length data) 0)
	do (print (length data))
	do (setf tmp (subseq data 0 bits))
	do (setf data (subseq data bits))
	do (loop while (> (length tmp) 1)
		do (setf part "")
		do (setf i 0)
		do (loop while (< i (length tmp))
			do (if (char= (char tmp i) (char tmp (+ i 1)))
				(setf part (concatenate 'string part "1"))
				(setf part (concatenate 'string part "0")))
			do (setf i (+ i 2)))
		do (setf tmp part))
	do (setf cksum (concatenate 'string cksum tmp)))

(print cksum)
